name: full_testing_flutter
description: Flutter App's simplest automated full test.
version: 1.0.0
author: Chinnon Santos <chinnonsantos@gmail.com>
homepage: https://www.chinnonsantos.com.br
repository: https://github.com/chinnonsantos/full_testing_flutter
issue_tracker: https://github.com/chinnonsantos/full_testing_flutter/issues

environment:
  sdk: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # https://pub.dev/packages/test
  test: ^1.9.4
  # https://pub.dev/packages/provider
  provider: ^6.1.2

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  # https://pub.dev/packages/pedantic
  pedantic: ^1.8.0+1

flutter:
  uses-material-design: true
