name: Coverage Check

on: [pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # Ensure write access for issues

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.22.1"

      - name: Install dependencies
        run: flutter pub get

      - name: Retrieve old lcov.info from base branch
        run: |
          git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge:
          git checkout FETCH_HEAD -- coverage/lcov.info
          mv coverage/lcov.info ./old_lcov.info || echo "No previous lcov.info found."

      - name: Run Coverage Check Script
        run: |
          chmod +x scripts/check_coverage.sh
          ./scripts/check_coverage.sh

      - name: Comment on PR with results
        uses: actions/github-script@v6
        with:
          script: |
            const testsPassed = process.env.TEST_CASES_PASSED;
            const diffPercentage = process.env.DIFF_PERCENTAGE;
            const commentBody = `Test Cases Passed: ${testsPassed}\nDifference in Coverage Percentage: ${diffPercentage}%`;
            
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody,
            });
